name: dandelion
version: git
summary: A fully programmable proxy
description: |
  A proxy where the rule can be defined with dynamic language for extreme flexibility

grade: stable
base: cor22
confinement: strict

parts:
  dandelion:
    plugin: rust
    rust-channel: stable
    source: core/
    build-packages:
      - pkg-config
      - libssl-dev

apps:
  dandelion:
    command: bin/dandelion
    daemon: simple
    plugs:
      - network
      - network-bind
