[package]
name = "specht2_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
tokio = { version = "1.14.0", features = ["io-util", "net", "macros", "rt", "rt-multi-thread"] }
thiserror = "1.0"
strum = { version = "0.22.0", features = ["derive"] }
async-trait = "0.1.51"
structopt = "0.3.25"
