[package]
name = "specht2_core"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
tokio = { version = "1.15.0", features = ["io-util", "net", "macros", "rt", "rt-multi-thread"] }
strum = { version = "0.23.0", features = ["derive"] }
async-trait = "0.1.52"
structopt = "0.3.25"
tokio-tungstenite = "0.16.1"
futures = "0.3.17"
async-compat = "0.2.1"
http = "0.2.5"
pin-project = "1.0.8"
chrono = "0.4.19"
hyper-tungstenite = "0.5.0"
hyper = { version = "0.14.16", features = ["http1", "server"] }
bytes = "1.1.0"
tungstenite = "0.16.0"
ron = "0.7.0"
serde = { version = "1.0.132", features = ["derive"] }
serde_with = "1.11.0"
log = "0.4.14"
flexi_logger = "0.22.0"
anyhow = "1.0.51"
tokio-native-tls = "0.3.0"
fdlimit = "0.2.1"
lazy_static = "1.4.0"
regex = "1.5.4"
ipnetwork = "0.18.0"
maxminddb = { version = "0.21.0", features = ["mmap"] }
iso3166-1 = "1.0.1"
flate2 = "1.0.22"
tar = "0.4.38"
reqwest = "0.11.7"
# Make sure it's compatible with maxminddb
memmap2 = "0.3.1"
serde_regex = "1.1.0"
async-recursion = "0.3.2"
tempfile = "3.2.0"
tower = { version = "0.4.11", features = ["util"] }
tokio-stream = { version = "0.1.8", features = ["net"] }

[dev-dependencies]
env_logger = "0.9.0"
rstest = "0.12.0"
test-log = "0.2.8"
