[package]
name = "specht2_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
tokio = { version = "1.14.0", features = ["io-util", "net", "macros", "rt", "rt-multi-thread"] }
thiserror = "1.0.30"
strum = { version = "0.23.0", features = ["derive"] }
async-trait = "0.1.51"
structopt = "0.3.25"
tokio-tungstenite = "0.16.0"
futures = "0.3.18"
async-compat = "0.2.1"
http = "0.2.5"
pin-project = "1.0.8"
chrono = "0.4.19"
hyper-tungstenite = "0.5.0"
hyper = { version = "0.14.15", features = ["http1", "server"] }
bytes = "1.1.0"
tungstenite = "0.16.0"
ron = "0.7.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_with = "1.11.0"
log = "0.4.14"
flexi_logger = "0.20.1"
