name: CI
on: [push]

jobs:
  check_rust:
    strategy:
      matrix:
        # The macos-latest tag currently refers to 10.15
        # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on
        os: [macos-11, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy, rustfmt
            override: true
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path core/Cargo.toml  -- --check
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --manifest-path core/Cargo.toml -- -D warnings
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path core/Cargo.toml -- --include-ignored
        env:
          MAXMINDDB_LICENSE: ${{ secrets.MAXMINDDB_LICENSE }}

  lint_swift:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
          working-directory: app
      - run: bundler exec fastlane lint
        working-directory: app

  test_app:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy, rustfmt
            override: true
            target: aarch64-apple-darwin
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
          working-directory: app
      - run: bundler exec fastlane ci
        working-directory: app

  release:
    runs-on: macos-11
    needs: [check_rust, lint_swift, test_app]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            target: aarch64-apple-darwin
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
          working-directory: app
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.MATCH_DEPLOY_KEY }}
      - run: bundler exec fastlane ci_release
        env:
          MATCH_READONLY: true
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        working-directory: app
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          files:
            app/Specht2.zip
            app/Specht2.app.dSYM.zip
      - name: update version information for sparkle
        run: app/bin/publish_appcast.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
