name: ci
on: [push]

jobs:
  check_rust:
    strategy:
      matrix:
        os: [macos-13, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # Rustls on windows depends on aws-lc, which depends on nasm.
      - uses: ilammy/setup-nasm@v1
        if: runner.os == 'Windows'
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            core
      - name: cargo fmt
        run: cargo fmt --all --manifest-path core/Cargo.toml -- --check
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features --manifest-path core/Cargo.toml -- -D warnings
      - name: cargo test
        if: ${{ env.MAXMINDDB_LICENSE != 0 }}
        run: cargo test --manifest-path core/Cargo.toml -- --include-ignored
        env:
          MAXMINDDB_LICENSE: ${{ secrets.MAXMINDDB_LICENSE }}
      - name: cargo test (no secrets)
        if: ${{ env.MAXMINDDB_LICENSE == 0 }}
        run: cargo test --manifest-path core/Cargo.toml -- --include-ignored
        env:
          MAXMINDDB_LICENSE: ${{ secrets.MAXMINDDB_LICENSE }}
          SKIP_MAXMINDDB_TESTS: 1

  docker:
    runs-on: ubuntu-latest
    needs: [check_rust]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          # We don't build docker image for other archs because it's toooooo slow.
          # You can build it yourself or use snap to install it.
          platforms: "linux/amd64"
          tags: ghcr.io/zhuhaow/dandelion:latest
          cache-from: type=registry,ref=ghcr.io/zhuhaow/dandelion:buildcache
          cache-to: type=registry,ref=ghcr.io/zhuhaow/dandelion:buildcache,mode=max
