name: Docker Release
on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          # We don't build docker image for other archs because it's toooooo slow.
          # You can build it yourself or use snap to install it.
          platforms: "linux/amd64"
          tags: ghcr.io/zhuhaow/specht2:${{ github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/zhuhaow/specht2:buildcache
          cache-to: type=registry,ref=ghcr.io/zhuhaow/specht2:buildcache,mode=max
